package de.prob2.ui.symbolic;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import de.prob2.ui.verifications.AbstractCheckableItem;

// Match property order that was previously generated by Gson
// (to avoid unnecessary reordering when re-saving existing files).
@JsonPropertyOrder({
	"type",
	"code",
	"selected",
})
public abstract class SymbolicItem extends AbstractCheckableItem {
	private final String code;
	private final SymbolicExecutionType type;

	public SymbolicItem(String code, SymbolicExecutionType type) {
		super();
		this.code = code;
		this.type = type;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public SymbolicExecutionType getType() {
		return type;
	}
	
	public boolean settingsEqual(final SymbolicItem other) {
		return this.getCode().equals(other.getCode())
			&& this.getType().equals(other.getType());
	}
	
	@Override
	public String toString() {
		return String.join(" ", this.getCode(), this.getType().name());
	}
}
