package de.prob2.ui.symbolic;

public interface SymbolicExecutionType {
	String getName();
	
	// Enum constant name.
	// This method is automatically generated by Java in the enum classes.
	String name();
}
