package de.prob2.ui.symbolic;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.google.common.base.MoreObjects;

import de.prob2.ui.verifications.AbstractCheckableItem;

// Match property order that was previously generated by Gson
// (to avoid unnecessary reordering when re-saving existing files).
@JsonPropertyOrder({
	"type",
	"code",
	"selected",
})
public abstract class SymbolicItem<T extends SymbolicExecutionType> extends AbstractCheckableItem {
	private final String code;

	public SymbolicItem(String code) {
		super();
		this.code = code;
	}
	
	public String getCode() {
		return this.code;
	}
	
	public abstract T getType();
	
	public boolean settingsEqual(final SymbolicItem<?> other) {
		return this.getCode().equals(other.getCode())
			&& this.getType().equals(other.getType());
	}
	
	@Override
	public String toString() {
		return MoreObjects.toStringHelper(this)
			.add("type", this.getType())
			.add("code", this.getCode())
			.toString();
	}
}
