package de.prob2.ui.verifications.symbolicchecking;

public enum SymbolicCheckingType {
	SEQUENCE,INVARIANT,DEADLOCK,FIND_DEADLOCK,FIND_VALID_STATE, CHECK_ALL_OPERATIONS, 
	FIND_REDUNDANT_INVARIANTS, CHECK_REFINEMENT, CHECK_ASSERTIONS, IC3, TINDUCTION, KINDUCTION, BMC
}
