package de.prob2.ui;

import javafx.application.Application;

/**
 * <p>This class provides a workaround for issue <a href="https://github.com/openjfx/javafx-gradle-plugin/issues/31">openjfx/javafx-gradle-plugin#31</a>. The tar/zip distribution launch scripts generated by Gradle do not put JavaFX on the module path. This causes problems, because Java 11 refuses to launch JavaFX applications (subclasses of {@link Application}) from the command line if JavaFX is not present on the module path.</p>
 * 
 * <p>However, this restriction does not apply when launching a JavaFX application manually using {@link Application#launch(Class, String...)}. This class provides a simple main method that launches our JavaFX application, and because the class itself does not extend {@link Application}, it can still be run from the command line even if JavaFX is not on the module path.</p>
 */
public final class Main {
	private Main() {
		throw new AssertionError();
	}

	public static void main(final String[] args) {
		Application.launch(ProB2.class, args);
	}
}
